# Site settings
title: Chadev
description: "A community for Chattanooga Developers"
url: http://chadev.github.io

# Links to include in header/footer
links:
  - title: Live
    url: /live
  - title: Devs
    url: /devs
  - title: Groups
    url: /groups
  - title: Events
    url: /events
  - title: Code of Conduct
    url: /coc
  - title: Jobs
    url: http://jobs.chadev.com
  - title: Slack
    url: https://join.slack.com/t/chadev/shared_invite/enQtNjc3NjAyODQyODk2LTdkZjA3ZjE5MDY1YTkzNmM4OWM4ZWVmZTY2ZTFjMTljMzIyMjQ1MTlhNGIzOWViMGUyYmMxZjM1YWE4ZTVkNjU

# Custom collection settings
collections:
  groups:
    output: false
  devs:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   bower.json
    -   bower.json
    -   gulpfile.js
    -   package.json

sass:
  sass_dir: assets/sass
  style: :compressed

# Gravatar vars
gravatar_sizes:
  devs: 300
  groups: 300
