# Site settings
title: Chadev
description: "A community for Chattanooga Developers"
url: http://chadev.github.io

# Links to include in header/footer
links:
  - title: Devs
    url: /devs
  - title: Groups
    url: /groups
  - title: Events
    url: /events
  - title: Resources
    url: /resources
  - title: Code of Conduct
    url: /coc

# Custom collection settings
collections:
  groups:
    output: false
  devs:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   bower.json
    -   bower.json
    -   gulpfile.js
    -   package.json

sass:
  sass_dir: css

# Gravatar vars
gravatar_sizes:
  devs: 300
  groups: 300
